name: Publish documentation
on: workflow_dispatch

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - id: pages
        uses: actions/configure-pages@v5
      - run: bun --bun turbo docs:build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: apps/docs/.vitepress/dist
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
